### ISSUE TITLE
Links to images don't work if redmine is not installed in root dir

### ISSUE THREAD

**Issue by alexander233** [opsct/redhopper#1]
Thank you very much for this great plugin. On our site the arrows for moving issues up and down etc. don't show up. This happens because the link to the icon is: 
`<img src="/images/sort_asc.png" alt="Move to top arrow" />`
However we used an installer from Bitnami, which does not install Redmine into the root directory but into /redmine/. The correct path would be: 
`<img src="/redmine/images/sort_asc.png" alt="Move to top arrow" />`

Here is an excerpt of the Kanban html source (links to redmine actions correctly prefix the /redmine/ path, it is only the icons where the root path is missing): 

```
<div class='sortable'>
<a title="Move to top" rel="nofollow" data-method="post" href="/redmine/redhopper_issues/move?id=2&amp;target_id=1"><img src="/images/sort_asc.png" alt="Move to top arrow" /></a>
<a title="Move up" rel="nofollow" data-method="post" href="/redmine/redhopper_issues/move?id=2&amp;target_id=1"><img src="/images/arrow_up.png" alt="Move up arrow" /></a>
<a title="Move back to unsorted section" rel="nofollow" data-method="delete" href="/redmine/redhopper_issues?id=2"><img src="/images/bullet_diamond.png" alt="Move back to unsorted section" /></a>
</div>
<p><a href="/redmine/issues/10">My current task</a></p>
<div class='issue-due-before' title='On time'>4d</div>
```
I have solved the issue on our site by just copying the icons to where your plugin expects them. They look great!

**Comment by opsct** [comment]
probably but this is just a mirror. please report this problem to the project: https://framagit.org/infopiiaf/redhopper/-/issues
